# Generated by Django 5.2.7 on 2025-10-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(help_text="Введите email", max_length=254, verbose_name="Электронная почта"),
                ),
                ("country", models.CharField(help_text="Введите страну", max_length=100, verbose_name="Страна")),
                ("city", models.CharField(help_text="Введите город", max_length=100, verbose_name="Город")),
                ("street", models.CharField(help_text="Введите улицу", max_length=100, verbose_name="Улица")),
                (
                    "house_number",
                    models.CharField(help_text="Введите номер дома", max_length=10, verbose_name="Номер дома"),
                ),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
    ]
