# Generated by Django 5.2.7 on 2025-10-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Введите название", max_length=255, verbose_name="Название")),
                ("model", models.CharField(help_text="Введите модель", max_length=100, verbose_name="Модель")),
                (
                    "release_date",
                    models.DateField(help_text="Введите дату выхода на рынок", verbose_name="Дата выхода на рынок"),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
