# Generated by Django 5.2.7 on 2025-10-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название компании", max_length=255, verbose_name="Название компании"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Введите задолженность перед поставщиком",
                        max_digits=10,
                        verbose_name="Задолженность",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(0, "Завод"), (1, "Розничная сеть"), (2, "Индивидуальный предприниматель")],
                        editable=False,
                        verbose_name="Уровень звена",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания")),
                (
                    "contacts",
                    models.ForeignKey(
                        help_text="Введите ID звена контактов",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="networks",
                        to="electro.contact",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        help_text="Введите ID продуктов",
                        related_name="networks",
                        to="electro.product",
                        verbose_name="Продукты",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите ID звена поставщика",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="networks",
                        to="electro.network",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "звено сети",
                "verbose_name_plural": "звенья сети",
            },
        ),
    ]
